scroll:
  duration: 2000
  updateHistory: false

nav:
  what: reserve
  why: why
  candidacy: candidatura
  testimonials: testimonials
  faq: faqs

join: https://cres-enquestesonline.iea.ad:4443/online.php?pid=BIOESFERA

external:
  exteriors_ods: https://www.exteriors.ad/ca/ods
  unesco_mab: https://en.unesco.org/mab
  reserves_network: https://en.unesco.org/biosphere/wnbr

mails:
  inquiry: info@andorrabiosfera.ad

social:
  # twitter: https://www.twitter.com/andorrabiosfera
  facebook: https://www.facebook.com/Andorra-Biosfera-105439151423742
  instagram: https://www.instagram.com/andorra.biosfera
  vimeo: https://www.vimeo.com/andorrabiosfera

goals:
  interval: 15 # seconds
  items:
    - id: commitment
      image: img/andorra_pano.jpg
    - id: balance
      image: img/cavalls.jpg
    - id: anticipation
      image: img/roc_quer.jpg
    - id: consensus
      image: img/claus.jpg

why:
  - id: importance
    images:
      - img/reserves_map.png
      - logos/unesco_mab.png
    paragraphs: 3
    layout: parallax-layout-1
    parallax: [0.1, 0.2]
  - id: reasons
    images:
      - img/correfocs.jpg
      - img/ovelles.jpg
      - img/trencalos.jpg
    paragraphs: 2
    layout: parallax-layout-2
    parallax: [0.1, 0.3, 0.2]
  - id: moment
    images:
      - img/panells_solars.jpg
      - img/riu.jpg
    paragraphs: 1
    layout: parallax-layout-3
    parallax: [0, 0.1, 0.2]

candidacy:
  video: https://player.vimeo.com/video/478582124?portrait=false&title=false&byline=false
  steps:
    diagnosis: 1598918400000
    diffusion: 1601510401000
    participation: 1612137600000
    synthesis: 1648803600000
    presentation: 1693558800000
    resolution: 1711962000000

  files:
    viability_study: docs/estudi_viabilitat_reserva_biosfera_andorra.pdf
    candidacy_slides: docs/presentacio_candidatura_reserva_biosfera_andorra.pdf
    survey_results: docs/resultats_enquesta.pdf
    press_kit_ca: docs/press_kit_ca.pdf
    press_kit_en: docs/press_kit_en.pdf
    # candidacy_dossier: null

testimonials:
  marc_font_ian_serra:
    name: Marc Font & Ian Serra
    file: entrevista_marc_font_ian_serra.pdf
  pilar_rodriguez:
    name: Pilar Rodriguez
    file: entrevista_pilar_rodriguez.pdf
  eva_choy:
    name: Eva Choy
    file: entrevista_eva_choy.pdf
  josep_majoral:
    name: Josep Majoral
    file: entrevista_josep_majoral.pdf
  josep_marticella:
    name: Josep Marticella
    file: entrevista_josep_marticella.pdf

coordination:
  leader: govern_andorra
  fellows:
    - ari
