nav:
  candidacy: candidatura
  faq: faqs

join: https://www.visc.ad

mails:
  inquiry: consultes@andorrabiosfera.ad

social:
  twitter: https://www.twitter.com/andorrabiosfera
  facebook: https://www.facebook.com/andorrabiosfera
  instagram: https://www.instagram.com/andorrabiosfera
  vimeo: https://www.vimeo.com/andorrabiosfera
  telegram: tg://resolve?domain=andorrabiosfera

candidacy:
  # https://player.vimeo.com/video/{id}?portrait=false&title=false&byline=false
  video: https://player.vimeo.com/video/471933158
  steps:
    diagnosis: 1598918400000
    diffusion: 1609459200000
    participation: 1612137600000
    synthesis: 1625097600000
    presentation: 1630454400000
    resolution: 1646006400000

  files:
    viability_study: docs/estudi_viabilitat.pdf
    candidacy_slides: docs/presentacio_reserva_biosfera.pdf
    participation_results: docs/resultats_proces_participatiu.zip
    candidacy_dossier: docs/dossier_candidatura.pdf
