scroll:
  duration: 2000
  updateHistory: false

nav:
  candidacy: candidatura
  faq: faqs

join: https://www.visc.ad

external:
  exteriors_ods: https://www.exteriors.ad/ca/ods
  unesco_mab: https://en.unesco.org/mab
  reserves_network: https://en.unesco.org/biosphere/wnbr

mails:
  inquiry: consultes@andorrabiosfera.ad

social:
  twitter: https://www.twitter.com/andorrabiosfera
  facebook: https://www.facebook.com/andorrabiosfera
  instagram: https://www.instagram.com/andorrabiosfera
  vimeo: https://www.vimeo.com/andorrabiosfera
  telegram: tg://resolve?domain=andorrabiosfera

goals:
  interval: 15 # seconds
  items:
    - id: commitment
      image: ''
    - id: sustainability
      image: ''
    - id: anticipation
      image: ''
    - id: consensus
      image: ''

why:
  - id: importance
    images:
      - https://instagram.fbcn9-1.fna.fbcdn.net/v/t51.2885-15/e35/58468432_629615587553649_1432855299155192112_n.jpg?_nc_ht=instagram.fbcn9-1.fna.fbcdn.net&_nc_cat=109&_nc_ohc=UesJUxpDTeUAX_0Bg1m&tp=18&oh=2bd7269f0a3ff530f1238c10dc433aaa&oe=5FD67239
      - https://images.unsplash.com/photo-1536048810607-3dc7f86981cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80
    layout: parallax-layout-1
    parallax: [0.1, 0.2]
  - id: reasons
    images:
      - https://images.unsplash.com/photo-1546778316-dfda79f1c84e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80
      - https://www.rostit.cat/img/ecudella-i-carn-d-olla.jpg
      - https://instagram.fbcn9-1.fna.fbcdn.net/v/t51.2885-15/e35/p1080x1080/124846857_305931627041572_4964708312118434375_n.jpg?_nc_ht=instagram.fbcn9-1.fna.fbcdn.net&_nc_cat=104&_nc_ohc=6iJjY0m5zTQAX8T98ci&tp=19&oh=2410c16fe7c6402cd25f550efa666ba5&oe=5FD56973
    layout: parallax-layout-2
    parallax: [0.1, 0.3, 0.2]
  - id: moment
    images:
      - https://instagram.fbcn9-1.fna.fbcdn.net/v/t51.2885-15/e35/58468432_629615587553649_1432855299155192112_n.jpg?_nc_ht=instagram.fbcn9-1.fna.fbcdn.net&_nc_cat=109&_nc_ohc=UesJUxpDTeUAX_0Bg1m&tp=18&oh=2bd7269f0a3ff530f1238c10dc433aaa&oe=5FD67239
      - https://images.unsplash.com/photo-1536048810607-3dc7f86981cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80
    layout: parallax-layout-3
    parallax: [0.1, 0.2]
  - id: network
    images:
      - reserves_map.png
      - unesco_mab.png
      - ods.png
    layout: parallax-layout-4
    parallax: [0.1, 0.2, 0.3]

candidacy:
  # https://player.vimeo.com/video/{id}?portrait=false&title=false&byline=false
  video: https://player.vimeo.com/video/471933158
  steps:
    diagnosis: 1598918400000
    diffusion: 1609459200000
    participation: 1612137600000
    synthesis: 1625097600000
    presentation: 1630454400000
    resolution: 1646006400000

  files:
    viability_study: docs/estudi_viabilitat.pdf
    candidacy_slides: docs/presentacio_reserva_biosfera.pdf
    participation_results: docs/resultats_proces_participatiu.zip
    candidacy_dossier: docs/dossier_candidatura.pdf
