mails:
  inquiry: consultes@andorrabiosfera.ad

social:
  twitter: https://www.twitter.com/andorrabiosfera
  facebook: https://www.facebook.com/andorrabiosfera
  instagram: https://www.instagram.com/andorrabiosfera
  vimeo: https://www.vimeo.com/andorrabiosfera
  telegram: tg://resolve?domain=andorrabiosfera
